name: research_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.1.2
  - cudatoolkit=11.3.1
  - matplotlib=3.5.1
  - numpy=1.21.6
  - setuptools==59.5.0
  - pip:
    - anytree==2.8.0
    - networkx==2.8
    - six==1.16.0
    - wheel==0.36.2